# Generated by Django 5.0.6 on 2024-12-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_remove_product_prodapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('door', 'Doors'), ('window', 'Windows'), ('furnicher', 'Furnichers'), ('textile', 'Textiles'), ('light', 'Lightings'), ('kichen', 'Kichen Accessories'), ('bathroom', 'Bathroom Accessories'), ('wall', 'Wall Decor')], max_length=10),
        ),
    ]
