# Generated by Django 5.0.6 on 2024-12-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
