# Generated by Django 5.0.6 on 2024-12-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_orderplaced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
