# Generated by Django 5.0.6 on 2024-12-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
