# Generated by Django 5.0.6 on 2024-12-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0017_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.product'),
        ),
    ]
