# Generated by Django 5.0.6 on 2024-12-29 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0019_alter_payment_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
