# Generated by Django 5.0.6 on 2025-01-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0021_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
