# Generated by Django 5.0.6 on 2025-01-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0024_alter_payment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='user',
        ),
    ]
